from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Optional

from contracts.resolver import STATUS_CODE_ONLY, STATUS_CONTRADICTION, ResolvedContract
from evidence.models import Evidence


@dataclass
class HealPlan:
    contract_id: str
    target_file: str
    find_text: str
    replace_text: str
    rationale: str
    confidence: float
    operation: str = "update"


def plan_doc_repair(resolved: ResolvedContract) -> Optional[HealPlan]:
    if resolved.status != STATUS_CONTRADICTION:
        return None
    if not resolved.contract.doc_evidence or not resolved.contract.code_evidence:
        return None

    doc_ev = resolved.contract.doc_evidence[0]
    code_ev = resolved.contract.code_evidence[0]

    return HealPlan(
        contract_id=resolved.contract.contract_id,
        target_file=doc_ev.provenance.file or "",
        find_text=str(doc_ev.value),
        replace_text=str(code_ev.value),
        rationale=(
            f"Code evidence ({code_ev.provenance.file}, confidence {code_ev.confidence}) "
            f"shows {code_ev.value!r}; documentation ({doc_ev.provenance.file}) claims "
            f"{doc_ev.value!r}."
        ),
        confidence=min(doc_ev.confidence, code_ev.confidence),
    )


def plan_document_creation(evidence: Iterable[Evidence], repo_name: str) -> Optional[HealPlan]:
    """Create a baseline reference only for source-backed, undocumented behavior."""
    sources = [
        item for item in evidence
        if item.provenance.source_type not in {"documentation", "test"}
    ]
    if not sources:
        return None

    lines = [
        "# Generated repository reference",
        "",
        f"This reference was generated by Cognis from implementation evidence in `{repo_name}`.",
        "Review it before publishing or committing it.",
        "",
        "## Observed implementation",
        "",
    ]
    for item in sources[:16]:
        location = item.provenance.file or item.subject
        line_range = ""
        if item.provenance.start_line:
            end = item.provenance.end_line or item.provenance.start_line
            line_range = f":{item.provenance.start_line}-{end}"
        value = item.value if isinstance(item.value, dict) else {}
        node_type = value.get("node_type", "source declaration")
        snippet = str(value.get("text", "")).strip().replace("\n", " ")
        summary = snippet[:180] if snippet else "Implementation evidence observed."
        lines.extend((f"- `{location}{line_range}` ({node_type}): `{summary}`", ""))

    lines.extend((
        "## Verification boundary",
        "",
        "This file is evidence-backed but generated. It should be reviewed before it becomes published documentation.",
        "",
    ))

    return HealPlan(
        contract_id="contract:generated:undocumented-behavior",
        target_file="docs/COGNIS_GENERATED.md",
        find_text="",
        replace_text="\n".join(lines),
        rationale=(
            f"Cognis found {len(sources)} source-backed behavior records in {repo_name} "
            "without an in-repository documentation surface to update."
        ),
        confidence=min(item.confidence for item in sources),
        operation="create",
    )
